apiVersion: v1
kind: Service
metadata:
  name: svc-web-login
  namespace: web
spec:
  type: NodePort
  clusterIP: 172.20.20.3
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    app: web-login
