apiVersion: v1
kind: Service
metadata:
  name: svc-web-order
  namespace: web
spec:
  type: NodePort
  clusterIP: 172.20.20.4
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    app: web-order
