apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was-signup
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-was-signup
  nfs:
    path: /dynamic_provisioning/signup
    server: fs-05f0e46aec263fa2a.efs.ap-northeast-2.amazonaws.com