apiVersion: v1
kind: Service
metadata:
  name: svc-web-reservation
  namespace: web
spec:
  type: NodePort
  clusterIP: 172.20.20.5
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    app: web-reservation
